server: 8080
spring:
  application:
    name: reminder
  datasource:
    url: jdbc:postgresql://localhost:5433/reminder
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.default_batch_fetch_size: 25
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  quartz:
    job-store-type: memory # или jdbc, если хочешь использовать БД
    scheduler-name: reminder-scheduler
    wait-for-jobs-to-complete-on-shutdown: false
    auto-startup: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: reminder-scheduler
          threadPool:
            threadCount: 2
            class: org.quartz.simpl.SimpleThreadPool
          jobStore:
            class: org.quartz.simpl.RAMJobStore
  mail:
    host: smtp.gmail.com
    port: 587
    username: danil18124@gmail.com 
    password: cwhj rdnm fwsn bfmp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true